name: Andreas M. Antonopoulos Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configurations for Andreas M. Antonopoulos
      run: |
        git config --local user.name "Andreas M. Antonopoulos"
        git config --local user.email "andreas@antonopoulos.com"

    - name: Create Bitcoin folders
      run: |
        mkdir -p Bitcoin/Development
        mkdir -p Bitcoin/Research

    - name: Add files for Bitcoin projects
      run: |
        touch Bitcoin/Development/README.md
        echo "Bitcoin Development" > Bitcoin/Development/README.md
        touch Bitcoin/Research/README.md
        echo "Bitcoin Research" > Bitcoin/Research/README.md

    - name: Push changes
      run: |
        git add .
        git commit -m "Set up Bitcoin's projects"
        git push
