name: Awesome Crypto Research Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configurations
      run: |
        # GitHub Actions Configuration
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"

        # Likhon Sheikh's Configuration
        git config --local user.name "Likhon Sheikh"
        git config --local user.email "isaac.likhon@yahoo.com"

        # Vitalik Buterin (Ethereum co-founder)
        git config --local user.name "Vitalik Buterin"
        git config --local user.email "vitalik@ethereum.org"

        # Gavin Wood (Polkadot co-founder)
        git config --local user.name "Gavin Wood"
        git config --local user.email "gavin@parity.io"

        # Charlie Lee (Litecoin creator)
        git config --local user.name "Charlie Lee"
        git config --local user.email "charlie@litecoin.org"

        # Andreas M. Antonopoulos (Bitcoin expert)
        git config --local user.name "Andreas M. Antonopoulos"
        git config --local user.email "andreas@antonopoulos.com"

        # Joseph Poon (Lightning Network co-author)
        git config --local user.name "Joseph Poon"
        git config --local user.email "joseph@lightning.network"

        # Justin Sun (TRON founder)
        git config --local user.name "Justin Sun"
        git config --local user.email "justin@tron.network"

        # Dan Larimer (EOS creator)
        git config --local user.name "Dan Larimer"
        git config --local user.email "dan@eos.io"

        # Andreas Schildbach (Bitcoin Wallet Developer)
        git config --local user.name "Andreas Schildbach"
        git config --local user.email "andreas@bitcoinwallet.com"

    - name: Create folder structure
      run: |
        mkdir -p SmartContracts/ETH/Contracts
        mkdir -p SmartContracts/BSC/Contracts
        mkdir -p SmartContracts/Polygon/Contracts
        mkdir -p BlockchainNetworks/Ethereum
        mkdir -p BlockchainNetworks/BinanceSmartChain
        mkdir -p BlockchainNetworks/Polygon
        mkdir -p Security/BestPractices
        mkdir -p Community/Contributors

    - name: Add main documentation files
      run: |
        echo "# Awesome Crypto Research" > README.md
        echo "This repository contains documentation, best practices, and contributions for various blockchain networks, smart contracts, and security." >> README.md
        echo "## Blockchain Networks" > BlockchainNetworks/README.md
        echo "This folder contains details about various blockchain networks such as Ethereum, BSC, Polygon, etc." >> BlockchainNetworks/README.md
        echo "## Smart Contract Best Practices" > Security/BestPractices/README.md
        echo "Best practices for developing secure and efficient smart contracts." >> Security/BestPractices/README.md
        touch Community/Contributors/README.md

    - name: Check if files exist before creating
      run: |
        if [ ! -f Security/BestPractices/SmartContractSecurity.md ]; then
          touch Security/BestPractices/SmartContractSecurity.md
        fi

    - name: Push changes if any
      run: |
        git add .
        git commit -m "Set up folder structure and documentation"
        git push

  fetch-community-contributions:
    runs-on: ubuntu-latest
    needs: setup-repo

    steps:
    - name: Fetch contributors from GitHub API
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/likhonsh3ikh/awesome-crypto-research/contributors" \
        -o contributors.json

    - name: Parse contributors and add to README
      run: |
        jq '.[] | .login' contributors.json | while read contributor; do
          echo "- $contributor" >> Community/Contributors/README.md
        done

    - name: Commit new contributors
      run: |
        git add Community/Contributors/README.md
        git commit -m "Updated contributors list"
        git push

  deploy-github-pages:
    runs-on: ubuntu-latest
    needs: setup-repo

    steps:
    - name: Create static website for GitHub Pages
      run: |
        mkdir -p GitHubPages
        echo "<!DOCTYPE html><html><head><title>Awesome Crypto Research</title></head><body><h1>Welcome to Awesome Crypto Research!</h1><script src='script.js'></script></body></html>" > GitHubPages/index.html
        echo "console.log('Welcome to Awesome Crypto Research!');" > GitHubPages/script.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./GitHubPages
