name: Charlie Lee Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configurations for Charlie Lee
      run: |
        git config --local user.name "Charlie Lee"
        git config --local user.email "charlie@litecoin.org"

    - name: Create Litecoin folders
      run: |
        mkdir -p Litecoin/Development
        mkdir -p Litecoin/Protocol

    - name: Add files for Litecoin projects
      run: |
        touch Litecoin/Development/README.md
        echo "Litecoin Development" > Litecoin/Development/README.md
        touch Litecoin/Protocol/README.md
        echo "Litecoin Protocol" > Litecoin/Protocol/README.md

    - name: Push changes
      run: |
        git add .
        git commit -m "Set up Litecoin's projects"
        git push
