name: Justin Sun Workflow

on:
  push:
    branches:
      - main

jobs:
  justin-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Git Config
      run: |
        git config --local user.name "Justin Sun"
        git config --local user.email "justin@tron.network"

    - name: Create TRON Folder Structure
      run: |
        mkdir -p Contributors/JustinSun/TRON
        echo "Justin Sun's TRON Contributions" > Contributors/JustinSun/TRON/README.md

    - name: Commit Changes
      run: |
        git add .
        git commit -m "Add Justin Sun's contributions folder"
        git push
