name: Changpeng Zhao Activity

on:
  push:
    branches:
      - main

jobs:
  user-activity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config --local user.name "Changpeng Zhao"
        git config --local user.email "cz@binance.com"

    - name: Create Binance Files
      run: |
        mkdir -p Binance/{Docs,Projects,Wallet}
        echo "Binance Wallet" > Binance/Wallet/README.md
        echo "Binance Documentation" > Binance/Docs/README.md
        git add .
        git commit -m "Added Binance structure for CZ"

    - name: Star Binance Smart Chain Repo
      uses: actions/github-script@v6
      with:
        script: |
          const owner = 'binance-chain';
          const repo = 'bsc';
          await github.rest.activity.starRepo({ owner, repo });

    - name: Push Changes
      run: git push
