name: Vitalik Buterin Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git configurations for Vitalik Buterin
      run: |
        git config --local user.name "Vitalik Buterin"
        git config --local user.email "vitalik@ethereum.org"

    - name: Create Ethereum folders
      run: |
        mkdir -p Ethereum/Development
        mkdir -p Ethereum/Research
        mkdir -p Ethereum/Protocol

    - name: Add files for Ethereum projects
      run: |
        touch Ethereum/Development/README.md
        echo "Ethereum Development" > Ethereum/Development/README.md
        touch Ethereum/Research/README.md
        echo "Ethereum Research" > Ethereum/Research/README.md
        touch Ethereum/Protocol/README.md
        echo "Ethereum Protocol" > Ethereum/Protocol/README.md

    - name: Push changes
      run: |
        git add .
        git commit -m "Set up Ethereum's projects"
        git push
