name: CZ Contributions

on:
  push:
    branches:
      - main

jobs:
  cz-contributions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config --local user.name "Changpeng Zhao"
        git config --local user.email "cz@binance.com"

    - name: Create Binance Files
      run: |
        mkdir -p Binance/{Docs,Projects,Wallet}
        echo "Binance Wallet Info" > Binance/Wallet/README.md
        echo "Documentation for Binance Projects" > Binance/Docs/README.md
        git add .
        git commit -m "Added Binance directory structure for CZ"

    - name: Fetch Public Repositories
      uses: actions/github-script@v6
      with:
        script: |
          const repos = await github.rest.repos.listForUser({
            username: 'cz_binance',
          });
          console.log(repos.data.map(repo => repo.name));
