name: Justin Sun Activity

on:
  push:
    branches:
      - main

jobs:
  user-activity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config --local user.name "Justin Sun"
        git config --local user.email "justin@tron.network"

    - name: Create TRON Files
      run: |
        mkdir -p Justin/TRON/{Protocol,Docs}
        echo "TRON Protocol Work" > Justin/TRON/Protocol/README.md
        git add .
        git commit -m "Justin Sun: Created TRON files"

    - name: Star TRON Repo
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.activity.starRepo({
            owner: 'tronprotocol',
            repo: 'java-tron'
          });

    - name: Push Changes
      run: git push
