name: Elon Musk Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-elon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Elon Musk related folders and files
      run: |
        mkdir -p "ElonMusk/Twitter"
        mkdir -p "ElonMusk/Tesla"
        mkdir -p "ElonMusk/SpaceX"
        mkdir -p "ElonMusk/Neuralink"

        echo "# Twitter Data" > "ElonMusk/Twitter/twitter_data.md"
        echo "Data and insights related to Twitter." >> "ElonMusk/Twitter/twitter_data.md"
        echo "# Tesla Projects" > "ElonMusk/Tesla/tesla_projects.md"
        echo "Projects and innovations by Tesla." >> "ElonMusk/Tesla/tesla_projects.md"
        echo "# SpaceX Projects" > "ElonMusk/SpaceX/spacex_projects.md"
        echo "Exploring the missions and innovations of SpaceX." >> "ElonMusk/SpaceX/spacex_projects.md"
        echo "# Neuralink Innovations" > "ElonMusk/Neuralink/neuralink_innovations.md"
        echo "Technological advancements in Neuralink." >> "ElonMusk/Neuralink/neuralink_innovations.md"

    - name: Commit and push Elon Musk's changes
      run: |
        git config --local user.name "Elon Musk"
        git config --local user.email "elonmusk@tesla.com"
        git add .
        git commit -m "Added folders and files for Elon Musk projects"
        git push
